# Generated by Django 5.2.3 on 2025-08-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetingrequest_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('getting-started', 'Getting Started'), ('account', 'Account & Billing'), ('services', 'Our Services'), ('technical', 'Technical Support'), ('general', 'General Questions')], max_length=20)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-helpful_votes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('startup', 'Startup'), ('enterprise', 'Enterprise')], max_length=20)),
                ('challenge', models.TextField(help_text='The problem we solved')),
                ('solution', models.TextField(help_text='How we solved it')),
                ('results', models.TextField(help_text='The outcomes achieved')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='case-studies/')),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('technologies_used', models.JSONField(default=list, help_text='List of technologies used')),
                ('project_duration', models.CharField(help_text="e.g., '3 months', '6 weeks'", max_length=50)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics', models.JSONField(default=dict, help_text='Key performance metrics')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testimonial')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
