# Generated by Django 5.2.3 on 2025-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companyinfo_featureflag_jobposition_navigationmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('about', 'About Section'), ('services', 'Services Section'), ('portfolio', 'Portfolio Section'), ('testimonials', 'Testimonials Section'), ('team', 'Team Section'), ('contact', 'Contact Section'), ('cta', 'Call to Action'), ('feature', 'Feature Section'), ('stats', 'Statistics Section'), ('blog', 'Blog Section'), ('gallery', 'Gallery Section'), ('faq', 'FAQ Section'), ('pricing', 'Pricing Section'), ('custom', 'Custom HTML')], max_length=20)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('services', 'Services Page'), ('portfolio', 'Portfolio Page'), ('team', 'Team Page'), ('contact', 'Contact Page'), ('blog', 'Blog Page'), ('careers', 'Careers Page')], max_length=20)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('subheading', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True, help_text='Custom HTML content')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='sections/videos/')),
                ('background_color', models.CharField(blank=True, default='#000000', max_length=7)),
                ('layout_style', models.CharField(default='default', max_length=50)),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes', max_length=500)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this section')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_on_mobile', models.BooleanField(default=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('button_style', models.CharField(default='primary', max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Additional section data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Section',
                'verbose_name_plural': 'Dynamic Sections',
                'ordering': ['page', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VisitorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('avg_session_duration', models.PositiveIntegerField(default=0)),
                ('home_views', models.PositiveIntegerField(default=0)),
                ('about_views', models.PositiveIntegerField(default=0)),
                ('services_views', models.PositiveIntegerField(default=0)),
                ('portfolio_views', models.PositiveIntegerField(default=0)),
                ('contact_views', models.PositiveIntegerField(default=0)),
                ('blog_views', models.PositiveIntegerField(default=0)),
                ('mobile_views', models.PositiveIntegerField(default=0)),
                ('desktop_views', models.PositiveIntegerField(default=0)),
                ('tablet_views', models.PositiveIntegerField(default=0)),
                ('direct_traffic', models.PositiveIntegerField(default=0)),
                ('search_traffic', models.PositiveIntegerField(default=0)),
                ('social_traffic', models.PositiveIntegerField(default=0)),
                ('referral_traffic', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor Statistics',
                'verbose_name_plural': 'Visitor Statistics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
