app = "agency-website"
primary_region = "sin"  # Singapore region, you can change this

[build]
  [build.args]
    NODE_VERSION = "20"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 5173
  processes = ["app"]

  [[services.ports]]
    port = 3000
    handlers = ["http"]
    force_https = true

[env]
  PORT = "8000"
  NODE_ENV = "production"