[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "frontend/functions"

[dev]
  command = "cd frontend && npm run dev"
  port = 8888
  targetPort = 5173

# Ignore Python dependencies for frontend build
[build.environment]
  PYTHON_VERSION = "3.11"