[build]
  builder = "heroku/buildpacks:20"

[deploy]
  startCommand = "cd backend && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn agency_backend.wsgi:application --bind 0.0.0.0:$PORT"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  PORT = "8000"