services:
  - type: web
    name: agency-website-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn agency_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://agency-website-frontend.onrender.com"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://agency-website-frontend.onrender.com

  - type: web
    name: agency-website-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: agency-website-backend
          property: url
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
