services:
  - type: web
    name: agency-website-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn agency_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - type: static
    name: agency-website-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: agency-website-backend
          property: url
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
